name: Ember Baker
description: Full-stack Web Developer for Cisco Systems
avatar: https://avatars3.githubusercontent.com/u/2651964?s=400&u=5961f5b08c165c66b688ff212bff117ed8f396e7&v=4
theme: jekyll-theme-minimal
